spring:
  application:
    name: employee-service
  server:
    port: 8080
  main:
    web-application-type: reactive
  mvc:
    problemdetails:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: authenticate-service        #Authenticate service routing
          uri: lb://authenticate-service
          predicates:
            - Path=/api/v1/authenticates/**
        - id: employee-service            #Employee service routing
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - StripPrefix=0
            - LogRequest
        - id: project-service             #Project service routing
          uri: lb://project-service
          predicates:
            - Path=/api/v1/project/**
        - id: department-service          #Department service routing
          uri: lb://department-service
          predicates:
            - Path=/api/v1/department/**
      server:
        webflux:
          default-filters[0]: PreserveHostHeader

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: API Gateway
    description: Microservice for managing routing for different services inside the application
    version: 1.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  use-management-port: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

jwt:
  secret: your-very-secure-secret-key-minimum-32-characters-long
  expiration: 36000000
  refresh:
    expiration: 604800000